### ISSUE TITLE
Fill-in-the-blank hints

### ISSUE THREAD

**Issue by racheldantzlerquill** [empirical-org/Empirical-Core#4905] opened 2019-01-07 16:46 UTC
**Describe the bug**
In Quill Connect, I want the concept feedback to appear when the student answers fill-in-the-blank questions incorrectly. There is already concept feedback available for the concepts "Singular Possessive" and "Plural Possessive," but the concept feedback doesn't show up when I play the question and put the wrong answer.

This is the lesson:
https://connect.quill.org/?#/admin/lessons/-LVcwSCZZ_cP_iWWJank

Here are the specific questions that should be getting concept feedback:
So many of the pine ___ needles have fallen.
One ___ buckle is broken.
His ___ windshield is covered in ice.
Three of my ___ cars wouldn’t start this morning!
All twelve of the ___ designs were different.
My ___ zipper got stuck.
All the winter ___ hoods are lined with fur.
Emily always borrows her ___ clothes.

**Comment by emilia-friedberg** [comment] 2019-01-07 21:14
Hey @racheldantzlerquill, I'm going to close this issue and move it to Notion because it's really a new feature and not a bug, but I'll get right on it.

**Closed by emilia-friedberg** 2019-01-07 21:14 UTC
