### ISSUE TITLE
Assigned Activities not showing up on student profile

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Empirical-Core#491] opened 2015-01-19 16:07 UTC
Steps to reproduce:

- Login as teacher
- Go to Activity Planner / Create a Unit
- Give it a name, select some activities, Continue
- Select a class, provide a date, hit "Assign"
- Login as a student in the class
- The assigned activites do not show under the Assigned Activities header

**Comment by RyanNovas** [comment] 2015-01-19 16:21
I just reproduced this. Resolving this should be a top priority.

**Comment by RyanNovas** [comment] 2015-01-19 16:34
On a second check, I failed to reproduce this. Rather I was affected by #492 when trying to access the demo account. @kriskelly are you sure you're not missing the assigned lesson because of the different naming convention within the Students profile vs. the teachers? (Which should be an issue of its own.)

**Comment by kriskelly** [comment] 2015-01-19 16:50
This is broken on develop and works on master. Displaying assigned activities still works, which I verified by assigning the activity on master then switching back to develop.

**Comment by RyanNovas** [comment] 2015-01-19 16:52
Ok, good catch.

On Mon, Jan 19, 2015 at 11:50 AM, Kristopher Kelly <notifications@github.com
> wrote:

> This is broken on develop and works on master. Displaying assigned
> activities still works, which I verified by assigning the activity on
> master then switching back to develop.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/empirical-org/Empirical-Core/issues/491#issuecomment-70524898>
> .
>



-- 
Ryan Novas
Director of Operations

Quill: Interactive Grammar
*Learn English grammar by writing sentences and proofreading passages.*
http://quill.org

Connect with us on Twitter! @Quill_Grammar
<https://twitter.com/Quill_Grammar>

Learn more about Quill: *https://www.youtube.com/watch?v=jrl7uvD3SVk
<https://www.youtube.com/watch?v=jrl7uvD3SVk>*

**Comment by kriskelly** [comment] 2015-01-19 16:57
@RyanNovas You should be able to see this bug on staging as well, that has the most up to date version of develop.

**Comment by RyanNovas** [comment] 2015-01-19 17:06
@kriskelly, I just verified it on staging.

On Mon, Jan 19, 2015 at 11:57 AM, Kristopher Kelly <notifications@github.com
> wrote:

> @RyanNovas <https://github.com/RyanNovas> You should be able to see this
> bug on staging as well, that has the most up to date version of develop.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/empirical-org/Empirical-Core/issues/491#issuecomment-70526127>
> .
>



-- 
Ryan Novas
Director of Operations

Quill: Interactive Grammar
*Learn English grammar by writing sentences and proofreading passages.*
http://quill.org

Connect with us on Twitter! @Quill_Grammar
<https://twitter.com/Quill_Grammar>

Learn more about Quill: *https://www.youtube.com/watch?v=jrl7uvD3SVk
<https://www.youtube.com/watch?v=jrl7uvD3SVk>*

**Comment by marcellosachs** [comment] 2015-01-19 19:57
@kriskelly @RyanNovas hey guys, fixing this now, should be ready soon...

**Comment by marcellosachs** [comment] 2015-01-19 22:23
@kriskelly @RyanNovas this should be fixed now...

**Comment by RyanNovas** [comment] 2015-01-19 22:34
Looks good to me.

**Closed by RyanNovas** 2015-01-19 22:34 UTC
