### ISSUE TITLE
BUG REPORT - "Assigning..." button does not change to "Assigned"

### ISSUE THREAD

**Issue by jenny-price** [empirical-org/Empirical-Core#3017] opened 2017-09-21 19:27 UTC
https://docs.google.com/document/d/1q-l77i8tlD4DprXdoZO3Nxb5u_0KSXWbsTXzMPlnwn0/edit

**Comment by jaredsilver** [comment] 2017-09-28 13:41
Closing this for now because I can no longer reproduce it locally after this week's merges into develop. If the issue occurs again, I can take another look into it.

**Closed by jaredsilver** 2017-09-28 13:41 UTC
Labels: bug
