### ISSUE TITLE
make teachers from school's with subscriptions automatically get premium

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#1783] opened 2016-11-07 15:39 UTC
The easiest way is probably to add a 'school subscription' column in the subscription table, then make a scheduled nightly task that checks for all teachers from said schools and gives them premium if they don't have it already.

**Comment by ddmck** [comment] 2016-11-10 16:47
Duplicate of https://github.com/empirical-org/Empirical-Core/issues/1762

**Closed by ddmck** 2016-11-10 16:47 UTC
