### ISSUE TITLE
Number of affected sequences not displaying for incorrect sequences

### ISSUE THREAD

**Issue by Hannahmonk** [empirical-org/Empirical-Core#4553] opened 2018-08-28 20:17 UTC
#### Expected Behaviour
The number of sequences affected by an incorrect sequence is displayed when I add an incorrect sequence for a question in staging-diagnostic.

#### Actual Behaviour
The red box around the affected students responses is there, but the number of sequences affected is not. This seems to only be happening for NEW diagnostic questions; for questions that were ported over to staging-diagnostic, the number of affected sequences IS displaying.

#### Steps to Reproduce
Go to this question and add an incorrect sequence: https://staging-diagnostic.quill.org/#/admin/questions/-LKY5nFmY3eyU96AP4-H/incorrect-sequences

#### Potential sources for the issue (filename, new features ect.)
NA
#### Link to any private details (teacher/student names and emails)
NA

**Comment by emilia-friedberg** [comment] 2018-08-29 14:55
@Hannahmonk and I can't reproduce this on any questions or incorrect sequences now so I think it may have been related to the prod CMS memory issues. closing for now.

**Comment by emilia-friedberg** [comment] 2018-08-30 19:05
Hannah and I can both see it on this page now: https://staging-diagnostic.quill.org/?#/admin/questions/-LKXzTjgc5wLmk4pNKGb/responses

Has to do with a 500 error coming from https://cms.quill.org/responses/-LKXzTjgc5wLmk4pNKGb/incorrect_sequence_affected_count

**Comment by emilia-friedberg** [comment] 2019-03-14 14:54
I can no longer reproduce this, so I'm going to close this issue and if it pops up again we can reopen it.

**Closed by emilia-friedberg** 2019-03-14 14:54 UTC
Labels: 3 - medium pri bug
