### ISSUE TITLE
500 Error for Students from a school

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#731] opened 2015-04-29 14:14 UTC
A number of students from one school reported getting 500 errors on April 23rd, around 8:20 pm EST

Can we find this in the logs and see whether it is connected to the username space issues?

Here is a link to the accounts that have reported the issue, password protected: https://docs.google.com/a/quill.org/document/d/1wqrjLHtWx8NX9tAp-lMMFBF-oQ_fiImrEUpS8jEDm20/edit?usp=sharing

**Comment by marcellosachs** [comment] 2015-04-29 16:35
It seems that this is being caused by Redis Connection Timeout Errors : 
![screen shot 2015-04-29 at 12 19 49 pm](https://cloud.githubusercontent.com/assets/1789723/7396058/1e3ef0bc-ee6c-11e4-9c7a-0490a6d5f635.png)
![screen shot 2015-04-29 at 12 20 48 pm](https://cloud.githubusercontent.com/assets/1789723/7396068/2f6e54c2-ee6c-11e4-9863-8e2bc48b1f07.png)

**Comment by marcellosachs** [comment] 2015-04-29 16:42
There are two potential solutions to this. I personally favor the latter : 

1) 
Reconfigure Redis to make it more Robust
Advantages : 
A) Can continue to use Redis to cache the student Profile (only place where redis is used).
Disadvantages : 
A) It might take a nontrivial amount of time to develop the familiarity with Redis that would enable this reconfiguration.
B) We will likely need to rewrite the student profile in React eventually anyways, to make it paginated (infinite scroll), as they are just getting longer and longer. When we rewrite it in react, it will no longer use the cache anyways, making our use of Redis obselete. In general the app (and web development in general) is moving towards single-page app structures, in which Redis cached html is obselete.

2) Rewrite the student profile in React to make it paginated (with an infinite scroll), removing the cache
advantages: 
Needs to be done eventually anyways
disadvantages:
Will take a nontrivial amount of time to do (3 to 6 days), though not necessarily more days than it would take to reconfigure Redis.

**Comment by petergault** [comment] 2015-05-14 20:51
@marcellosachs It seems the the strategy here is to move the student scorebook to React, it seems like a better solution for growing the page as the page becomes more complex.

**Closed** 2015-06-12 23:23 UTC
