### ISSUE TITLE
Bugs in Activating Trial

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1574] opened 2016-08-18 23:07 UTC
There are currently three bugs bugs with the premium trial activation. 

# The Card on the dashboard is broken. 
- [x] The premium trial card in the dashboard is not showing up. It loads briefly and then disappears. It should stay open because I'm a new user. 
**Note: I am not sure if the activate trial card on the dashboard is hidden until a student completes an activity. If so, ignore this point.** 

# The Premium page trial is broken. 
- [ ] If I click on "trial" from the premium page, it loads the progress reports but it does not load premium. The button seems to be broken. 

# The Sign Up from the Premium Report is Broken
- [ ] When you click "start trial" it says sucess. However, once you click on it again, it goes back to saying start trial. 

![screen shot 2016-08-18 at 6 45 30 pm](https://cloud.githubusercontent.com/assets/3667179/17793646/eccabee8-6576-11e6-8542-4fd55cf1384f.png)

![screen shot 2016-08-18 at 6 45 34 pm](https://cloud.githubusercontent.com/assets/3667179/17793650/f16d3bec-6576-11e6-99d9-cf8c06ed5be4.png)

Note: Users do get the email campaign once they press the "start trial" from the premium report.

# To Reproduce
To reproduce, create a new user and try to start the trial.

**Comment by RyanNovas** [comment] 2016-08-19 16:11
The first issue is by design -- we don't show the banner unless they've completed a number of activities as the data is of limited benefit without that experience/data set.

The second is resolved by PR #1576

**Closed by RyanNovas** 2016-08-19 16:11 UTC
Labels: bug, Priority: ★
