### ISSUE TITLE
Bug Report: International Users Can't Add School by Zipcode

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4794] opened 2018-11-19 16:04 UTC
**Describe the bug**
An International school is not recognized in our "find your school by zip code" finder. This means that the teachers cannot access the Premium features that they purchased. 

**To Reproduce**
See Google Doc

**Expected behavior**
As a user, when you type in the school's zip code, you should be able to add your school if it's in our system. 

**Impact**
International users with School Premium subscriptions cannot access their Premium features 

**Screenshots**
See Google Doc

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
https://docs.google.com/document/d/121ZCqOnhu2D6paGZdeIPWJCDWHkCQk41IE3tYEXmr98/edit

**Comment by buckmaxwell** [comment] 2018-11-19 16:23
@maddymaher this is not a bug, let's talk over slack. closing.

**Closed by buckmaxwell** 2018-11-19 16:23 UTC
