### ISSUE TITLE
Bug Report: ELL Diagnostic Preview displaying 500 error message 

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4750] opened 2018-10-29 16:21 UTC
Once teachers complete the ELL Diagnostic preview, they receive a 500 error message. This does not necessarily block teachers in any way, but it confuses them and makes them concerned that students will not be able to complete the assignment.

#### Link to any private details (teacher/student names and emails)
https://docs.google.com/document/d/1RF6ZOBXom4iqVBWhIc1xWw07jiG63-vwE0A9xqgSgu8/edit?usp=sharing

**Comment by buckmaxwell** [comment] 2018-10-29 18:09
@maddymaher @ddmck  -- wasn't this issue opened before? (and I thought closed?)

**Comment by buckmaxwell** [comment] 2018-10-29 18:10
Is it the same as this? https://github.com/empirical-org/Empirical-Core/issues/4648

**Comment by maddymaher** [comment] 2018-10-30 15:57
@buckmaxwell yeah, this is the same issue. This is a good process question - if a closed bug comes up again, should I file a new bug report or open the closed one? @SaraQuill @ddmck

**Comment by SaraQuill** [comment] 2018-10-30 19:00
My initial thought would be to comment on the old bug and then the eng team
can decide whether or not to re-open. It'd also be helpful to find out why
we closed, e.g. if we believed it was fixed or if we couldn't repro so we
didn't try to fix.
ᐧ

**Comment by buckmaxwell** [comment] 2018-10-30 19:11
@SaraQuill @maddymaher -- either one is fine.  It's best to reopen an old bug if you know it exists.  Whenever you do something (close or open) it's good to say why. I like to add something like 'closed due to inactivity' or 'closed due to lack of intercom reports' or 'closed -- pull request made'.

**Comment by buckmaxwell** [comment] 2018-10-30 19:13
closing because this is a duplicate of an older issue #4648

**Comment by maddymaher** [comment] 2018-11-15 22:00
@buckmaxwell @ddmck Its back (scared face emoji). Not high-pri, though.

**Comment by tomcalabrese** [comment] 2018-11-16 20:57
For the impact aspect of this bug — had a couple more teachers having this issue and able to replicate consistently.

**Closed** 2019-03-01 17:23 UTC
