### ISSUE TITLE
Bug Report: Submit button not working for Starter and Intermediate Diagnostics (Beta)

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4841] opened 2018-12-03 21:07 UTC
**Describe the bug**
On some questions, the submit button will not work, and thus doesn't let you move to the next question. There have been a few different reports, and there are people getting stuck on different questions every time 
**To Reproduce**
See google doc 

**Expected behavior**

**Impact**
If the submit button does not work, people cannot finish the activity, and thus we will not receive sufficient feedback on the Starter Diagnostic. 

**Screenshots**
See google doc 

**Additional context**
https://docs.google.com/document/d/1kHCLstWflGdwubMMRVGKV-j0l9VUj0CZJ2q0InHOMK4/edit?usp=sharing

**Comment by emilia-friedberg** [comment] 2018-12-05 20:34
I think we figured out the cause of this (no optimal response) so I'm closing the issue.

**Closed by emilia-friedberg** 2018-12-05 20:34 UTC
