### ISSUE TITLE
Bug report: teacher's diagnostic results keep disappearing

### ISSUE THREAD

**Issue by maddymaher** [empirical-org/Empirical-Core#4577] opened 2018-09-05 20:50 UTC
I have restored this teacher's diagnostic results multiple times, and they keep appearing and then disappearing

#### Link to any private details (teacher/student names and emails)
https://docs.google.com/document/d/1C0LQauxbC6aBZYuonPiYDLGDqk4N12KPzoCHbPBdnos/edit?usp=sharing

**Comment by ddmck** [comment] 2018-09-11 21:53
duplicate of https://github.com/empirical-org/Empirical-Core/issues/4584

**Closed by ddmck** 2018-09-11 21:53 UTC
