### ISSUE TITLE
Feature: Landing page after signing up for free trial of premium

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#4197] opened 2018-05-08 01:48 UTC
# Feature Spec:
In order to quickly show teachers the value of premium
As a first step after signing up a free trial
Teachers should be sent to the premium reports

# Scenario :
Given I am a teacher 
And I am on the Premium info page
When I click on “Free Trial” 
Then I should be sent to the “Activity Scores Report” page
And I should see a banner that shows I have 30 days left in my trial and links to details on premium pricing and the upgrade page.

**Comment by RyanNovas** [comment] 2018-05-09 14:37
@ddmck seems to be a duplicate of #4212 which @emilia-friedberg just took care of

**Closed by RyanNovas** 2018-05-09 14:37 UTC
