### ISSUE TITLE
Add error page tracking 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1161] opened 2016-01-11 01:08 UTC
- [ ] Fire a Segment ever every time the LMS loads the 500 page. 
- [ ] Fire a segment event every time the LMS loads a "Heroku Application Error" page.

**Comment by marcellosachs** [comment] 2016-01-12 21:59
500 error tracking is done, implemented in the app (with associated spec).
Heroku Application Error is also done, implemented by changing the javascript in our error.html file on amazon s3 - https://s3.amazonaws.com/compass-files/error.html
(mixpanel javascript was removed, segment javascript was added, segment Heroku Error Page event firing included)

**Comment by marcellosachs** [comment] 2016-02-02 22:03
duplicate of #1193

**Closed by marcellosachs** 2016-02-02 22:03 UTC
Labels: awaiting approval to be closed
